Repository szkola-reacta/team-d-app, pull requests merged in 2020-11, with the labels that each got.

#11 Feature/3 create header
  package.json
  src/App.css
  src/App.js
  src/components/Header/Header.js
  src/components/Header/assets/travel.jpg
  src/components/Header/index.js
  src/components/Header/style.css
  src/components/Nav/Logo.js
  src/components/Nav/Nav.js
  src/components/Nav/NavIcon.js
  src/components/Nav/NavItem.js
  src/components/Nav/NavList.js
  src/components/Nav/assets/menu-c.svg
  src/components/Nav/assets/menu-o.svg
  src/components/Nav/index.js
  src/components/Nav/style.css
  yarn.lock
Labels: enhancement

#17 Update README.md
  README.md
Labels: documentation

#16 Feature/4 create footer
  src/App.js
  src/assets/github.svg
  src/components/Footer/Footer.js
  src/components/Footer/footerBreak/FooterBreak.js
  src/components/Footer/footerBreak/index.js
  src/components/Footer/footerBreak/style.css
  src/components/Footer/footerSection/FooterSection.js
  src/components/Footer/footerSection/index.js
  src/components/Footer/footerSection/style.css
  src/components/Footer/index.js
  src/components/Footer/socialLink/SocialLink.js
  src/components/Footer/socialLink/index.js
  src/components/Footer/socialLink/style.css
  src/components/Footer/style.css
Labels: enhancement

#25 Hotfix/24 resolve paths
  src/App.js
  src/components/Footer/FooterBreak/FooterBreak.js
  src/components/Footer/FooterBreak/index.js
  src/components/Footer/FooterBreak/style.css
  src/components/Footer/FooterSection/FooterSection.js
  src/components/Footer/FooterSection/index.js
  src/components/Footer/FooterSection/style.css
  src/components/Footer/SocialLink/SocialLink.js
  src/components/Footer/SocialLink/index.js
  src/components/Footer/SocialLink/style.css
Labels: bug

#21 Feature/8 create searchbar
  src/App.js
  src/components/Searchbar/ClearInput.js
  src/components/Searchbar/InputField.js
  src/components/Searchbar/ResultField.js
  src/components/Searchbar/Searchbar.js
  src/components/Searchbar/dummyData.js
  src/components/Searchbar/searchbar.css
Labels: enhancement

#23 Feature/19 refactor nav
  src/components/Nav/Nav.js
  src/components/Nav/NavItem.js
  src/components/Nav/NavList.js
  src/components/Nav/style.css
Labels: enhancement

#34 Configure ESLint settings in package.json (14)
  package.json
Labels: enhancement

#35 Feature/15 create jsconfig
  jsconfig.json
  src/App.js
  src/components/Footer/Footer.js
  src/components/Header/Header.js
Labels: enhancement

#33 Feature/13 adjust public folder
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
Labels: enhancement

#36 Add NavList to footer as a menu and fix styling (20)
  src/components/Footer/Footer.js
  src/components/Footer/style.css
Labels: enhancement

#51 Fix: #49 aesthetic refactor
  package.json
  src/App.js
  src/components/Footer/Footer.js
  src/components/Footer/FooterBreak/FooterBreak.js
  src/components/Footer/SocialLink/SocialLink.js
  src/components/Header/Header.js
  src/components/Nav/Logo.js
  src/components/Nav/Nav.js
  src/components/Nav/NavIcon.js
  src/components/Nav/NavItem.js
  src/components/PageNotFound/PageNotFound.js
  src/components/Searchbar/ClearInput.js
  src/components/Searchbar/InputField.js
  src/components/Searchbar/ResultField.js
  src/components/Searchbar/Searchbar.js
  src/containers/About.js
Labels: enhancement

#32 Created database.json with sample data and Place Component to display this data. For now only for mobile view
  package.json
  public/API/database.json
  public/index.html
  src/App.js
  src/App.test.js
  src/components/Place/Place.js
  src/components/Place/PlaceComponents/PlaceContainer.js
  src/components/Place/PlaceComponents/PlaceDetails/PlaceDescription.js
  src/components/Place/PlaceComponents/PlaceDetails/PlaceHeader.js
  src/components/Place/PlaceComponents/PlaceDetails/PlacePhoto.js
  src/components/Place/PlaceComponents/PlaceDetails/index.js
  src/components/Place/PlaceComponents/PlaceDetails/style.css
  src/components/Place/PlaceComponents/index.js
  src/components/Place/PlaceComponents/style.css
  src/components/Place/index.js
  src/setupTests.js
  yarn.lock
Labels: enhancement
